### ISSUE TITLE
E_ERROR in some servers

### ISSUE THREAD

**Issue by dbjpanda** [actions-pack/feedbacks#77]
```
An error of type E_ERROR was caused in line 264 of the file /home/wplive/web/wp-live/wp-content/plugins/actions-pack-premium/plugin.php. Error message: Uncaught Error: Call to undefined method Symfony\Component\Finder\SplFileInfo::getFilenameWithoutExtension() in /home/wplive/web/wp-live/wp-content/plugins/actions-pack-premium/plugin.php:264
Stack trace:
#0 /home/wplive/web/wp-live/wp-content/plugins/actions-pack-premium/plugin.php(249): Actions_Pack::initClasses('\\Actions_Pack\\D...', '/home/wplive/we...')
#1 /home/wplive/web/wp-live/wp-includes/class-wp-hook.php(308): Actions_Pack->{closure}(Object(Elementor\Core\DynamicTags\Manager))
#2 /home/wplive/web/wp-live/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#3 /home/wplive/web/wp-live/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#4 /home/wplive/web/wp-live/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(328): do_action_ref_array('elementor/dynam...', Array)
#5 /home/wplive/web/wp-live/wp-content/plugins/elementor/core/dynamic-tags/manager.php(257): Elementor\Modules\DevTools\Deprecation->do_deprecated_action('elementor/dynam...', Array, '3.5.0', 'elementor/
```

**Comment by dbjpanda** [comment]
init.php 

Replace 

```php
public static function initClasses(string $namespace, string $path = __DIR__): array {
        $finder = new Symfony\Component\Finder\Finder();
        $finder->files()->in($path)->name('*.php');
        foreach ($finder as $file) {
            $class_name = rtrim($namespace, '\\') . '\\' . $file->getFilenameWithoutExtension();
            if (class_exists($class_name)) {
                try {
                    $objects[] = new $class_name();
                }
                catch (\Throwable $e) {
                    continue;
                }
            }
        }
        return $objects ?? [];
    }
```
    
    with 

```php
public static function initClasses(string $namespace, string $path = __DIR__): array {
    $objects = [];

    $dir_iterator = new RecursiveDirectoryIterator($path);
    $iterator = new RecursiveIteratorIterator($dir_iterator, RecursiveIteratorIterator::SELF_FIRST);
    foreach ($iterator as $file) {
        if ($file->isFile() && $file->getExtension() === 'php') {
            $class_name = rtrim($namespace, '\\') . '\\' . $file->getBasename('.php');
            if (class_exists($class_name)) {
                try {
                    $objects[] = new $class_name();
                } catch (\Throwable $e) {
                    continue;
                }
            }
        }
    }

    return $objects;
}
```
